import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaolucas
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtVal1 = new javax.swing.JLabel();
        cxVal1 = new javax.swing.JTextField();
        rtVal2 = new javax.swing.JLabel();
        cxVal2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cxResult = new javax.swing.JTextField();
        btSoma = new javax.swing.JButton();
        btSub = new javax.swing.JButton();
        btMult = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtVal1.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        rtVal1.setText("Valor1");

        cxVal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVal1ActionPerformed(evt);
            }
        });

        rtVal2.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        rtVal2.setText("Valor2");

        cxVal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVal2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setText("Resultado");

        cxResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxResultActionPerformed(evt);
            }
        });

        btSoma.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        btSoma.setText("+");
        btSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomaActionPerformed(evt);
            }
        });

        btSub.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        btSub.setText("-");
        btSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubActionPerformed(evt);
            }
        });

        btMult.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        btMult.setText("*");
        btMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultActionPerformed(evt);
            }
        });

        btDiv.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        btDiv.setText("/");
        btDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSoma)
                        .addGap(18, 18, 18)
                        .addComponent(btSub)
                        .addGap(18, 18, 18)
                        .addComponent(btMult)
                        .addGap(18, 18, 18)
                        .addComponent(btDiv))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cxResult, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtVal1)
                                .addComponent(rtVal2))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxVal1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(cxVal2)))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtVal1)
                    .addComponent(cxVal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtVal2)
                    .addComponent(cxVal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSoma)
                    .addComponent(btSub)
                    .addComponent(btMult)
                    .addComponent(btDiv))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxVal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxVal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxVal1ActionPerformed

    private void cxVal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxVal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxVal2ActionPerformed

    private void cxResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxResultActionPerformed

    private void btSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomaActionPerformed
        // TODO add your handling code here:
        somar();
    }//GEN-LAST:event_btSomaActionPerformed

    private void btSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubActionPerformed
        // TODO add your handling code here:
        subtrair();
    }//GEN-LAST:event_btSubActionPerformed

    private void btMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultActionPerformed
        // TODO add your handling code here:
        multiplicar();
    }//GEN-LAST:event_btMultActionPerformed

    private void btDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivActionPerformed
        // TODO add your handling code here:
        dividir();
    }//GEN-LAST:event_btDivActionPerformed
    
    public void somar(){
        try{
            int a = Integer.parseInt( cxVal1.getText());
            int b = Integer.parseInt( cxVal2.getText());
            int c = (a+b);

            cxResult.setText(Integer.toString(c));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "O valor deve ser um inteiro",
                    "Erro de Entrada",
                     JOptionPane.ERROR_MESSAGE
            );
            cxVal1.requestFocus();
        }
    }
    
    public void subtrair(){
        try{
            int a = Integer.parseInt( cxVal1.getText());
            int b = Integer.parseInt( cxVal2.getText());
            int c = (a-b);

            cxResult.setText(Integer.toString(c));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "O valor deve ser um inteiro",
                    "Erro de Entrada",
                     JOptionPane.ERROR_MESSAGE
            );
            cxVal1.requestFocus();
        }
    }
    
    public void multiplicar(){
        try{
            int a = Integer.parseInt( cxVal1.getText());
            int b = Integer.parseInt( cxVal2.getText());
            int c = (a*b);

            cxResult.setText(Integer.toString(c));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "O valor deve ser um inteiro",
                    "Erro de Entrada",
                     JOptionPane.ERROR_MESSAGE
            );
            cxVal1.requestFocus();
        }
    }
    
    public void dividir(){
        try{
            int a = Integer.parseInt( cxVal1.getText());
            int b = Integer.parseInt( cxVal2.getText());
            int c = (a/b);

            cxResult.setText(Integer.toString(c));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                    null,
                    "O valor deve ser um inteiro",
                    "Erro de Entrada",
                     JOptionPane.ERROR_MESSAGE
            );
            cxVal1.requestFocus();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btMult;
    private javax.swing.JButton btSoma;
    private javax.swing.JButton btSub;
    private javax.swing.JTextField cxResult;
    private javax.swing.JTextField cxVal1;
    private javax.swing.JTextField cxVal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rtVal1;
    private javax.swing.JLabel rtVal2;
    // End of variables declaration//GEN-END:variables
}
