// João Lucas Silva de Souza; RA: 2649250

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaolucas
 */
public class FormRelSamambaia extends javax.swing.JFrame {
    
    private Samambaia s1 = new Samambaia();
    private static FormRelSamambaia cadUnic; //1º passo
    private BdSamambaia oprSam = BdSamambaia.geraOprSam();
    

    private FormRelSamambaia() { //2º passo
        initComponents();
        listTab();
    }

    public static FormRelSamambaia geraRelSam(){ //3º passo
        if(cadUnic == null){
            cadUnic = new FormRelSamambaia();
        }
        return cadUnic;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelSamambaia.class.getName());

    /**
     * Creates new form RelSamambaia
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspRelSam = new javax.swing.JScrollPane();
        tbSam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbSam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Grupo", "Tam Folha", "Tipo Fol", "Temp ideal", "Ilumin amb", "Cômodo", "Andar", "Tamanho"
            }
        ));
        jspRelSam.setViewportView(tbSam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspRelSam, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspRelSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbSam.getModel();
        
        int posLin = 0;
        modTab.setRowCount(posLin);
        
        for(Samambaia s1 : oprSam.getBdSam()){
            modTab.insertRow(posLin, new Object[]{s1.getNome(), s1.getGrupoPlanta(), s1.getTamanho(), s1.getTamFolha(), 
                s1.getTipoFolhagem(), s1.getAmbiente().getIluminacao(), s1.getAmbiente().getTemperatura(), s1.getAmbiente().getLocalizacao().getNomeComodo(), s1.getAmbiente().getLocalizacao().getAndarComodo(),});
            posLin++;
        }
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        listTab();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelSamambaia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspRelSam;
    private javax.swing.JTable tbSam;
    // End of variables declaration//GEN-END:variables
}
