// Versão NetBeans: 26
// João Lucas Silva de Souza; RA: 2649250

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/** 
 *
 * @author joaolucas
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormPrin = new javax.swing.JLabel();
        mnBarPrin = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        cadAnturio = new javax.swing.JMenuItem();
        cadCacto = new javax.swing.JMenuItem();
        cadSamambaia = new javax.swing.JMenuItem();
        menRelPlantas = new javax.swing.JMenu();
        relAnturio = new javax.swing.JMenuItem();
        relCacto = new javax.swing.JMenuItem();
        relSamambaia = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormPrin.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 24)); // NOI18N
        lblFormPrin.setText("Formulário Principal");

        mnCad.setText("Cadastros");
        mnCad.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 0, 18)); // NOI18N
        mnCad.setHideActionText(true);
        mnCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cadAnturio.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 15)); // NOI18N
        cadAnturio.setText("Anturio...");
        cadAnturio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAnturioActionPerformed(evt);
            }
        });
        mnCad.add(cadAnturio);

        cadCacto.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 15)); // NOI18N
        cadCacto.setText("Cacto...");
        cadCacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCactoActionPerformed(evt);
            }
        });
        mnCad.add(cadCacto);

        cadSamambaia.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 15)); // NOI18N
        cadSamambaia.setText("Samambaia...");
        cadSamambaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSamambaiaActionPerformed(evt);
            }
        });
        mnCad.add(cadSamambaia);

        menRelPlantas.setText("Relatório de plantas");
        menRelPlantas.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 15)); // NOI18N

        relAnturio.setText("Anturio...");
        relAnturio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relAnturioActionPerformed(evt);
            }
        });
        menRelPlantas.add(relAnturio);

        relCacto.setText("Cacto...");
        relCacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relCactoActionPerformed(evt);
            }
        });
        menRelPlantas.add(relCacto);

        relSamambaia.setText("Samambaia...");
        relSamambaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relSamambaiaActionPerformed(evt);
            }
        });
        menRelPlantas.add(relSamambaia);

        mnCad.add(menRelPlantas);

        menSair.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 15)); // NOI18N
        menSair.setText("Sair...");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        mnCad.add(menSair);

        mnBarPrin.add(mnCad);

        setJMenuBar(mnBarPrin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblFormPrin)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(lblFormPrin)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadCactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCactoActionPerformed
        // TODO add your handling code here:
        FormCadCacto.geraCadCac().setVisible(true);
    }//GEN-LAST:event_cadCactoActionPerformed

    private void cadAnturioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAnturioActionPerformed
        // TODO add your handling code here:
        FormCadAnturio.geraCadAnt().setVisible(true);
    }//GEN-LAST:event_cadAnturioActionPerformed

    private void cadSamambaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSamambaiaActionPerformed
        // TODO add your handling code here:
        FormCadSamambaia.geraCadSam().setVisible(true);
    }//GEN-LAST:event_cadSamambaiaActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_menSairActionPerformed

    private void relAnturioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relAnturioActionPerformed
        // TODO add your handling code here:
        FormRelAnturio.geraRelAnt().setVisible(true);
    }//GEN-LAST:event_relAnturioActionPerformed

    private void relCactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relCactoActionPerformed
        // TODO add your handling code here:
        FormRelCacto.geraRelCac().setVisible(true);
    }//GEN-LAST:event_relCactoActionPerformed

    private void relSamambaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relSamambaiaActionPerformed
        // TODO add your handling code here:
        FormRelSamambaia.geraRelSam().setVisible(true);
    }//GEN-LAST:event_relSamambaiaActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadAnturio;
    private javax.swing.JMenuItem cadCacto;
    private javax.swing.JMenuItem cadSamambaia;
    private javax.swing.JLabel lblFormPrin;
    private javax.swing.JMenu menRelPlantas;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JMenuBar mnBarPrin;
    private javax.swing.JMenu mnCad;
    private javax.swing.JMenuItem relAnturio;
    private javax.swing.JMenuItem relCacto;
    private javax.swing.JMenuItem relSamambaia;
    // End of variables declaration//GEN-END:variables
}
