// João Lucas Silva de Souza; RA: 2649250

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaolucas
 */
public class FormCadAnturio extends javax.swing.JFrame {
    private Anturio a1 = new Anturio();
    private static FormCadAnturio cadUnic; //1º passo
    private BdAnturio oprAnt = BdAnturio.geraOprAnt();
    

    private FormCadAnturio() { //2º passo
        initComponents();
    }

    public static FormCadAnturio geraCadAnt(){ //3º passo
        if(cadUnic == null){
            cadUnic = new FormCadAnturio();
        }
        return cadUnic;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadAnturio.class.getName());

    /**
     * Creates new form CadAnturio
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblCorFlor = new javax.swing.JLabel();
        lblFormFlor = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblIlumAmb = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        lblAndar = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtGrp = new javax.swing.JTextField();
        txtCorFlor = new javax.swing.JTextField();
        txtFormFlor = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtIlumAmb = new javax.swing.JTextField();
        txtCom = new javax.swing.JTextField();
        txtAndar = new javax.swing.JTextField();
        txtTam = new javax.swing.JTextField();
        btInsere = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlter = new javax.swing.JButton();
        btRmv = new javax.swing.JButton();
        jspAnt = new javax.swing.JScrollPane();
        tbAnt = new javax.swing.JTable();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblNome.setText("Nome");

        lblGrupo.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblGrupo.setText("Grupo");

        lblCorFlor.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblCorFlor.setText("Cor da flor");

        lblFormFlor.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblFormFlor.setText("Formato da flor");

        lblTemp.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTemp.setText("Temperatura ideal");

        lblIlumAmb.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblIlumAmb.setText("Iluminação do ambiente");

        lblCom.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblCom.setText("Cômodo");

        lblAndar.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblAndar.setText("Andar");

        lblTam.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTam.setText("Tamanho");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrpActionPerformed(evt);
            }
        });

        txtCorFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorFlorActionPerformed(evt);
            }
        });

        txtFormFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormFlorActionPerformed(evt);
            }
        });

        txtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempActionPerformed(evt);
            }
        });

        txtIlumAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIlumAmbActionPerformed(evt);
            }
        });

        txtCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComActionPerformed(evt);
            }
        });

        txtAndar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAndarActionPerformed(evt);
            }
        });

        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });

        btInsere.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btInsere.setText("Insere");
        btInsere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsereActionPerformed(evt);
            }
        });

        btCons.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btCons.setText("Consulta");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlter.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btAlter.setText("Altera");
        btAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterActionPerformed(evt);
            }
        });

        btRmv.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btRmv.setText("Remove");
        btRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvActionPerformed(evt);
            }
        });

        tbAnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Grupo", "Cor flor", "Form Flor", "Temp ideal", "Ilumin amb", "Cômodo", "Andar", "Tamanho"
            }
        ));
        jspAnt.setViewportView(tbAnt);

        btLimpar.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspAnt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblGrupo)
                                    .addComponent(lblCorFlor)
                                    .addComponent(lblFormFlor)
                                    .addComponent(lblTemp))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFormFlor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorFlor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGrp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIlumAmb)
                                    .addComponent(lblCom)
                                    .addComponent(lblTam)
                                    .addComponent(lblAndar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAndar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                    .addComponent(txtCom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIlumAmb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTam))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInsere)
                            .addComponent(btCons)
                            .addComponent(btAlter)
                            .addComponent(btRmv)
                            .addComponent(btSair)
                            .addComponent(btLimpar))
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrupo)
                            .addComponent(txtGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btInsere)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorFlor)
                    .addComponent(txtCorFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCons))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormFlor)
                            .addComponent(txtFormFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btAlter)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemp)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIlumAmb)
                            .addComponent(txtIlumAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btRmv)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCom)
                    .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAndar)
                            .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTam)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btSair)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrpActionPerformed

    private void txtCorFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorFlorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorFlorActionPerformed

    private void txtFormFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormFlorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormFlorActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtIlumAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIlumAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIlumAmbActionPerformed

    private void txtComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComActionPerformed

    private void txtAndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAndarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAndarActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void btInsereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsereActionPerformed
        // TODO add your handling code here
        insAnt();
        listTab();
        
    }//GEN-LAST:event_btInsereActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvActionPerformed
        // TODO add your handling code here:
        excAntNome();
        listTab();
    }//GEN-LAST:event_btRmvActionPerformed

    private void btAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterActionPerformed
        // TODO add your handling code here:
        atualizaAntNome();
        listTab();
    }//GEN-LAST:event_btAlterActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        // TODO add your handling code here
        consAntNome();
    }//GEN-LAST:event_btConsActionPerformed
    
    public void listTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbAnt.getModel();
        
        int posLin = 0;
        modTab.setRowCount(posLin);
        
        for(Anturio a1 : oprAnt.getBdAnt()){
            modTab.insertRow(posLin, new Object[]{a1.getNome(), a1.getGrupoPlanta(), a1.getCorFlor(), a1.getFormatoFlor(), 
                a1.getAmbiente().getTemperatura(), a1.getAmbiente().getIluminacao(), a1.getAmbiente().getLocalizacao().getNomeComodo(), a1.getAmbiente().getLocalizacao().getAndarComodo(), a1.getTamanho()});
            posLin++;
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    public void excAntNome(){
        a1 = new Anturio();

            a1.setNome(txtNome.getText());

            a1 = oprAnt.delAntNome(a1);
            
            if(a1 == null){
                JOptionPane.showMessageDialog(
                    null,
                    "Anturio apagado com sucesso!",
                    "Deleção de Anturio",
                    JOptionPane.INFORMATION_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe anturio com este nome!",
                        "Deleção de Anturio",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
        }
    
    public void atualizaAntNome(){
        a1 = new Anturio();
            a1.setNome(txtNome.getText());
            
            a1 = oprAnt.atualizaAntNome(a1);
            
            if(a1 != null){
                dados();
                JOptionPane.showMessageDialog(
                    null,
                    "Anturio atualizado! Confira os dados",
                    "Alteração de Anturio",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
             }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe anturio com esse nome!",
                        "Alteração de Anturio",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
                
            }
    }
    
    public void consAntNome(){
        a1 = new Anturio();
        
        a1.setNome((txtNome.getText()));
        
        a1 = oprAnt.consAntNome(a1);
        
        if(a1 != null){
            
            dados();
            JOptionPane.showMessageDialog(
                    null,
                    "Anturio encontrado com sucesso!",
                    "Consulta de Anturio",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe anturio com este nome!",
                        "Consulta de Anturio",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }        
    }
    
        public void insAnt() {
        a1 = new Anturio();

        try {
            a1.setNome(txtNome.getText());
            a1.setGrupoPlanta(txtGrp.getText());
            a1.setCorFlor(txtCorFlor.getText());
            // Polimorfismo sobrescrita
            a1.regar();
            a1.setFormatoFlor(txtFormFlor.getText());
            // Reflexividade
            a1.getAmbiente().setTemperatura(Float.parseFloat(txtTemp.getText()));
            a1.getAmbiente().setIluminacao(txtIlumAmb.getText());
            a1.getAmbiente().getLocalizacao().setNomeComodo(txtCom.getText());
            a1.getAmbiente().getLocalizacao().setAndarComodo(Integer.parseInt(txtAndar.getText()));

            boolean tamanhoValido = false;
            while (!tamanhoValido) {
                try {
                    int tamanho = Integer.parseInt(txtTam.getText());
                    a1.setTamanho(tamanho);
                    tamanhoValido = true;

                } catch (NumberFormatException nfe) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        "Valor inválido! Tamanho deve ser um número inteiro.",
                        "Erro de Formato",
                        JOptionPane.ERROR_MESSAGE
                    );
                    txtTam.setText(novoValor);

                } catch (TamNegException | TamGrdException e) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        e.getMessage() + "\nPor favor, digite um novo valor:",
                        "Erro no Tamanho",
                        JOptionPane.WARNING_MESSAGE
                    );
                    txtTam.setText(novoValor);
                }
            }

            a1 = oprAnt.insAnt(a1);

            if (a1 != null) {
                JOptionPane.showMessageDialog(
                    null,
                    "Cadastro realizado com sucesso!",
                    "Inserção de Anturio",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Nome já existe!",
                    "Inserção de Anturio",
                    JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }

        }// fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                null,
                "Erro de formato (provável inserção de letra ao invés de número) em um dos campos. Verifique os valores de Andar ou Temperatura.",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    public void dados(){
        txtNome.setText(a1.getNome());
        txtGrp.setText(a1.getGrupoPlanta());
        txtCorFlor.setText(a1.getCorFlor());
        txtFormFlor.setText(a1.getFormatoFlor());
        txtTemp.setText(Float.toString(a1.getAmbiente().getTemperatura()));
        txtIlumAmb.setText(a1.getAmbiente().getIluminacao());
        txtCom.setText(a1.getAmbiente().getLocalizacao().getNomeComodo());
        txtAndar.setText(Integer.toString(a1.getAmbiente().getLocalizacao().getAndarComodo()));
        txtTam.setText(Double.toString(a1.getTamanho()));
    }
    
    
    public void limpar(){
        txtNome.setText("");
        txtGrp.setText("");
        txtCorFlor.setText("");
        txtFormFlor.setText("");
        txtTemp.setText("");
        txtIlumAmb.setText("");
        txtCom.setText("");
        txtAndar.setText("");
        txtTam.setText("");
        txtNome.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadAnturio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlter;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btInsere;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRmv;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jspAnt;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblCorFlor;
    private javax.swing.JLabel lblFormFlor;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblIlumAmb;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTam;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JTable tbAnt;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtCorFlor;
    private javax.swing.JTextField txtFormFlor;
    private javax.swing.JTextField txtGrp;
    private javax.swing.JTextField txtIlumAmb;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTam;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
