// João Lucas Silva de Souza; RA: 2649250

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaolucas
 */
public class FormCadSamambaia extends javax.swing.JFrame {
    private Samambaia s1 = new Samambaia();
    private static FormCadSamambaia cadUnic; //1º passo
    private BdSamambaia oprSam = BdSamambaia.geraOprSam();
    

    private FormCadSamambaia() { //2º passo
        initComponents();
    }

    public static FormCadSamambaia geraCadSam(){ //3º passo
        if(cadUnic == null){
            cadUnic = new FormCadSamambaia();
        }
        return cadUnic;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadSamambaia.class.getName());

    /**
     * Creates new form CadAnturio
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblTamFol = new javax.swing.JLabel();
        lblTipFol = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblIlumAmb = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        lblAndar = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtGrp = new javax.swing.JTextField();
        txtTamFol = new javax.swing.JTextField();
        txtTipFol = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtCom = new javax.swing.JTextField();
        txtAndar = new javax.swing.JTextField();
        txtTam = new javax.swing.JTextField();
        btInsere = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlter = new javax.swing.JButton();
        btRmv = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jspSam = new javax.swing.JScrollPane();
        tbSam = new javax.swing.JTable();
        txtIlumAmb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblNome.setText("Nome");

        lblGrupo.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblGrupo.setText("Grupo");

        lblTamFol.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTamFol.setText("Tamanho da folha");

        lblTipFol.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTipFol.setText("Tipo folhagem");

        lblTemp.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTemp.setText("Temperatura ideal");

        lblIlumAmb.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblIlumAmb.setText("Iluminação do ambiente");

        lblCom.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblCom.setText("Cômodo");

        lblAndar.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblAndar.setText("Andar");

        lblTam.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTam.setText("Tamanho");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrpActionPerformed(evt);
            }
        });

        txtTamFol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamFolActionPerformed(evt);
            }
        });

        txtTipFol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipFolActionPerformed(evt);
            }
        });

        txtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempActionPerformed(evt);
            }
        });

        txtCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComActionPerformed(evt);
            }
        });

        txtAndar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAndarActionPerformed(evt);
            }
        });

        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });

        btInsere.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btInsere.setText("Insere");
        btInsere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsereActionPerformed(evt);
            }
        });

        btCons.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btCons.setText("Consulta");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlter.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btAlter.setText("Altera");
        btAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterActionPerformed(evt);
            }
        });

        btRmv.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btRmv.setText("Remove");
        btRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tbSam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Grupo", "Tam folha", "Tipo Fol", "Temp ideal", "Ilumin amb", "Cômodo", "Andar", "Tamanho"
            }
        ));
        jspSam.setViewportView(tbSam);

        txtIlumAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIlumAmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInsere)
                                .addGap(18, 18, 18)
                                .addComponent(btCons))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAndar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCom)
                                            .addComponent(lblTam))
                                        .addGap(171, 171, 171)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                            .addComponent(txtCom)
                                            .addComponent(txtTam)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblIlumAmb)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIlumAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNome)
                                                .addComponent(lblGrupo)
                                                .addComponent(lblTamFol)
                                                .addComponent(lblTipFol)
                                                .addComponent(lblTemp))
                                            .addGap(61, 61, 61)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtTipFol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                                .addComponent(txtTamFol, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtGrp, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTemp)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(btAlter)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLimpar)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btSair)
                                    .addComponent(btRmv))))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jspSam)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(txtGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamFol)
                    .addComponent(txtTamFol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInsere)
                    .addComponent(btCons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipFol)
                    .addComponent(txtTipFol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAlter)
                            .addComponent(btRmv))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSair)
                            .addComponent(btLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemp)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIlumAmb)
                            .addComponent(txtIlumAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCom)
                            .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAndar)
                            .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTam)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jspSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrpActionPerformed

    private void txtTamFolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamFolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamFolActionPerformed

    private void txtTipFolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipFolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipFolActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComActionPerformed

    private void txtAndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAndarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAndarActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void txtIlumAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIlumAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIlumAmbActionPerformed

    private void btAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterActionPerformed
        // TODO add your handling code here:
        atualizaSamNome();
        listTab();
    }//GEN-LAST:event_btAlterActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        // TODO add your handling code here:
        consSamNome();
    }//GEN-LAST:event_btConsActionPerformed

    private void btInsereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsereActionPerformed
        // TODO add your handling code here:
        insSam();
        listTab();
    }//GEN-LAST:event_btInsereActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvActionPerformed
        // TODO add your handling code here:
        excSamNome();
        listTab();
    }//GEN-LAST:event_btRmvActionPerformed
    
    public void listTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbSam.getModel();
        
        int posLin = 0;
        modTab.setRowCount(posLin);
        
        for(Samambaia s1 : oprSam.getBdSam()){
            modTab.insertRow(posLin, new Object[]{s1.getNome(), s1.getGrupoPlanta(), s1.getTamFolha(), s1.getTipoFolhagem(), 
                s1.getAmbiente().getTemperatura(), s1.getAmbiente().getIluminacao(), s1.getAmbiente().getLocalizacao().getNomeComodo(), s1.getAmbiente().getLocalizacao().getAndarComodo(), s1.getTamanho()});
            posLin++;
        }
    }
    
    public void excSamNome(){
        s1 = new Samambaia();

            s1.setNome(txtNome.getText());

            s1 = oprSam.delSamNome(s1);
            
            if(s1 == null){
                JOptionPane.showMessageDialog(
                    null,
                    "Samambaia apagada com sucesso!",
                    "Deleção de Samambaia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe samamabaia com este nome!",
                        "Deleção de Samambaia",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
        }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
       
    public void atualizaSamNome(){
        s1 = new Samambaia();
        s1.setNome(txtNome.getText());
            
        s1 = oprSam.atualizaSamNome(s1);
            
        if(s1 != null){
            txtNome.setText(s1.getNome());
            JOptionPane.showMessageDialog(
                null,
                "Samambaia atualizado! Confira os dados",
                "Alteração de Samambaia",
               JOptionPane.INFORMATION_MESSAGE
            );
            txtNome.setText("");
            txtNome.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe samambaia com esse nome!",
                        "Alteração de Samambaia",
                        JOptionPane.ERROR_MESSAGE
                );
                
            }
    }
    
    public void consSamNome(){
        s1 = new Samambaia();
        
        s1.setNome((txtNome.getText()));
        
        s1 = oprSam.consSamNome(s1);
        
        if(s1 != null){
           
            dados();
            JOptionPane.showMessageDialog(
                    null,
                    "Samambaia encontrado com sucesso!",
                    "Consulta de Samambaia",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe samambaia com este nome!",
                        "Consulta de Samambaia",
                        JOptionPane.ERROR_MESSAGE
                );
            }        
    }
    
    public void insSam(){
        s1 = new Samambaia();
        
        try{
            s1.setNome(txtNome.getText());
            s1.setGrupoPlanta(txtGrp.getText());
            s1.setTamFolha(Integer.parseInt(txtTamFol.getText()));
            // Polimorfismo sobrescrita
            s1.regar();
            s1.setTipoFolhagem(txtTipFol.getText());
            // Reflexividade
            s1.getAmbiente().setTemperatura(Float.parseFloat(txtTemp.getText()));
            s1.getAmbiente().setIluminacao(txtIlumAmb.getText());
            s1.getAmbiente().getLocalizacao().setNomeComodo(txtCom.getText());
            s1.getAmbiente().getLocalizacao().setAndarComodo(Integer.parseInt(txtAndar.getText()));
            
            boolean tamanhoValido = false;
            while (!tamanhoValido) {
                try {
                    int tamanho = Integer.parseInt(txtTam.getText());
                    s1.setTamanho(tamanho);
                    tamanhoValido = true;

                } catch (NumberFormatException nfe) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        "Valor inválido! Tamanho deve ser um número inteiro.",
                        "Erro de Formato",
                        JOptionPane.ERROR_MESSAGE
                    );
                    txtTam.setText(novoValor);

                } catch (TamNegException | TamGrdException e) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        e.getMessage() + "\nPor favor, digite um novo valor:",
                        "Erro no Tamanho",
                        JOptionPane.WARNING_MESSAGE
                    );
                    txtTam.setText(novoValor);
                }
            }

            s1 = oprSam.insSam(s1);

            if(s1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Cadastro realizado com sucesso!",
                        "Inserção de Samambaia",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Nome já existe!",
                        "Inserção de Samambaia",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
        }//fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                null,
                "Erro de formato (provável inserção de letra ao invés de número) em um dos campos. Verifique os valores de Andar, Tamanho Folha ou Temperatura.",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }   
    
    public void limpar(){
        txtNome.setText("");
        txtGrp.setText("");
        txtTamFol.setText("");
        txtTipFol.setText("");
        txtTemp.setText("");
        txtIlumAmb.setText("");
        txtCom.setText("");
        txtAndar.setText("");
        txtTam.setText("");
        txtNome.requestFocus();
    }
    
    public void dados(){
        txtNome.setText(s1.getNome());
        txtGrp.setText(s1.getGrupoPlanta());
        txtTamFol.setText(Integer.toString(s1.getTamFolha()));
        txtTipFol.setText((s1.getTipoFolhagem()));
        txtTemp.setText(Float.toString(s1.getAmbiente().getTemperatura()));
        txtIlumAmb.setText(s1.getAmbiente().getIluminacao());
        txtCom.setText(s1.getAmbiente().getLocalizacao().getNomeComodo());
        txtAndar.setText(Integer.toString(s1.getAmbiente().getLocalizacao().getAndarComodo()));
        txtTam.setText(Double.toString(s1.getTamanho()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadSamambaia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlter;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btInsere;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRmv;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jspSam;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblIlumAmb;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTam;
    private javax.swing.JLabel lblTamFol;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTipFol;
    private javax.swing.JTable tbSam;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtGrp;
    private javax.swing.JTextField txtIlumAmb;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTam;
    private javax.swing.JTextField txtTamFol;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtTipFol;
    // End of variables declaration//GEN-END:variables
}
