// João Lucas Silva de Souza; RA: 2649250

import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaolucas
 */
public class FormCadCacto extends javax.swing.JFrame {
    private Cacto c1 = new Cacto();
    private static FormCadCacto cadUnic; //1º passo
    private BdCacto oprCac = BdCacto.geraOprCac();
    

    private FormCadCacto() { //2º passo
        initComponents();
    }

    public static FormCadCacto geraCadCac(){ //3º passo
        if(cadUnic == null){
            cadUnic = new FormCadCacto();
        }
        return cadUnic;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadCacto.class.getName());

    /**
     * Creates new form CadAnturio
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblTolSeca = new javax.swing.JLabel();
        lblQntEsp = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblIlumAmb = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        lblAndar = new javax.swing.JLabel();
        lblTam = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtGrp = new javax.swing.JTextField();
        txtTolSeca = new javax.swing.JTextField();
        txtQuantEsp = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        txtIlumAmb = new javax.swing.JTextField();
        txtCom = new javax.swing.JTextField();
        txtTam = new javax.swing.JTextField();
        btInsere = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlter = new javax.swing.JButton();
        btRmv = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jspCac = new javax.swing.JScrollPane();
        tbCac = new javax.swing.JTable();
        txtAndar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblNome.setText("Nome");

        lblGrupo.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblGrupo.setText("Grupo");

        lblTolSeca.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTolSeca.setText("Tolerancia seca");

        lblQntEsp.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblQntEsp.setText("Quantidade de espinhos");

        lblTemp.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTemp.setText("Temperatura ideal");

        lblIlumAmb.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblIlumAmb.setText("Iluminação do ambiente");

        lblCom.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblCom.setText("Cômodo");

        lblAndar.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblAndar.setText("Andar");

        lblTam.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        lblTam.setText("Tamanho");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrpActionPerformed(evt);
            }
        });

        txtTolSeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTolSecaActionPerformed(evt);
            }
        });

        txtQuantEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantEspActionPerformed(evt);
            }
        });

        txtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempActionPerformed(evt);
            }
        });

        txtIlumAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIlumAmbActionPerformed(evt);
            }
        });

        txtCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComActionPerformed(evt);
            }
        });

        txtTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamActionPerformed(evt);
            }
        });

        btInsere.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btInsere.setText("Insere");
        btInsere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsereActionPerformed(evt);
            }
        });

        btCons.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btCons.setText("Consulta");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlter.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btAlter.setText("Altera");
        btAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterActionPerformed(evt);
            }
        });

        btRmv.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btRmv.setText("Remove");
        btRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Adwaita Sans", 1, 17)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        tbCac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Grupo", "Tolerancia s", "Quant espin", "Temp ideal", "Ilumin amb", "Cômodo", "Andar", "Tamanho"
            }
        ));
        jspCac.setViewportView(tbCac);

        txtAndar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAndarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jspCac)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIlumAmb)
                                    .addComponent(lblCom)
                                    .addComponent(lblTam)
                                    .addComponent(lblAndar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIlumAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                    .addComponent(txtCom)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblGrupo)
                                    .addComponent(lblTolSeca)
                                    .addComponent(lblQntEsp)
                                    .addComponent(lblTemp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtQuantEsp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTolSeca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGrp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSair)
                            .addComponent(btRmv)
                            .addComponent(btCons)
                            .addComponent(btAlter)
                            .addComponent(btInsere)
                            .addComponent(btLimpar))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrupo)
                            .addComponent(txtGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTolSeca)
                            .addComponent(txtTolSeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQntEsp)
                            .addComponent(txtQuantEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemp)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIlumAmb)
                            .addComponent(txtIlumAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCom)
                            .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAndar)
                            .addComponent(txtAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTam)
                            .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jspCac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btInsere)
                        .addGap(18, 18, 18)
                        .addComponent(btAlter)
                        .addGap(18, 18, 18)
                        .addComponent(btCons)
                        .addGap(18, 18, 18)
                        .addComponent(btRmv)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrpActionPerformed

    private void txtTolSecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTolSecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTolSecaActionPerformed

    private void txtQuantEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantEspActionPerformed

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void txtIlumAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIlumAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIlumAmbActionPerformed

    private void txtComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComActionPerformed

    private void txtTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamActionPerformed

    private void btInsereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsereActionPerformed
        // TODO add your handling code here:
        insCac();
        listTab();
        
    }//GEN-LAST:event_btInsereActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        // TODO add your handling code here:
        consCacNome();
    }//GEN-LAST:event_btConsActionPerformed

    private void btAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterActionPerformed
        // TODO add your handling code here:
        atualizaCacNome();
        listTab();
    }//GEN-LAST:event_btAlterActionPerformed

    private void btRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvActionPerformed
        // TODO add your handling code here:
        excCacNome();
        listTab();
    }//GEN-LAST:event_btRmvActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void txtAndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAndarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAndarActionPerformed
    
    public void listTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbCac.getModel();
        
        int posLin = 0;
        modTab.setRowCount(posLin);
        
        for(Cacto c1 : oprCac.getBdCac()){
            modTab.insertRow(posLin, new Object[]{c1.getNome(), c1.getGrupoPlanta(), c1.getToleranciaSeca(), c1.getQuantEspinhos(), 
                c1.getAmbiente().getTemperatura(), c1.getAmbiente().getIluminacao(), c1.getAmbiente().getLocalizacao().getNomeComodo(), c1.getAmbiente().getLocalizacao().getAndarComodo(), c1.getTamanho()});
            posLin++;
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    public void excCacNome(){
        c1 = new Cacto();

            c1.setNome(txtNome.getText());

            c1 = oprCac.delCacNome(c1);
            
            if(c1 == null){
                JOptionPane.showMessageDialog(
                    null,
                    "Cacto apagado com sucesso!",
                    "Deleção de Cacto",
                    JOptionPane.INFORMATION_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe cacto com este nome!",
                        "Deleção de Cacto",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }
        }
    
    public void atualizaCacNome(){
        c1 = new Cacto();
            c1.setNome(txtNome.getText());
            
            c1 = oprCac.atualizaCacNome(c1);
            
            if(c1 != null){
                dados();
                JOptionPane.showMessageDialog(
                    null,
                    "Cacto atualizado! Confira os dados",
                    "Alteração de Cacto",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
             }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe cacto com esse nome!",
                        "Alteração de Cacto",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
                
            }
    }
    
    public void consCacNome(){
        c1 = new Cacto();
        
        c1.setNome((txtNome.getText()));
        
        c1 = oprCac.consCacNome(c1);
        
        if(c1 != null){
            
            dados();
            JOptionPane.showMessageDialog(
                    null,
                    "Cacto encontrado com sucesso!",
                    "Consulta de Cacto",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        }
            else{
                JOptionPane.showMessageDialog(
                        null,
                        "Não existe cacto com este nome!",
                        "Consulta de Cacto",
                        JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }        
    }
    
        public void insCac() {
        c1 = new Cacto();

        try {
            c1.setNome(txtNome.getText());
            c1.setGrupoPlanta(txtGrp.getText());
            c1.setToleranciaSeca(txtTolSeca.getText());
            // Polimorfismo sobrescrita
            c1.regar();
            c1.setQuantEspinhos(Integer.parseInt(txtQuantEsp.getText()));
            // Reflexividade
            c1.getAmbiente().setTemperatura(Float.parseFloat(txtTemp.getText()));
            c1.getAmbiente().setIluminacao(txtIlumAmb.getText());
            c1.getAmbiente().getLocalizacao().setNomeComodo(txtCom.getText());
            c1.getAmbiente().getLocalizacao().setAndarComodo(Integer.parseInt(txtAndar.getText()));

            boolean tamanhoValido = false;
            while (!tamanhoValido) {
                try {
                    int tamanho = Integer.parseInt(txtTam.getText());
                    c1.setTamanho(tamanho);
                    tamanhoValido = true;

                } catch (NumberFormatException nfe) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        "Valor inválido! Tamanho deve ser um número inteiro.",
                        "Erro de Formato",
                        JOptionPane.ERROR_MESSAGE
                    );
                    txtTam.setText(novoValor);

                } catch (TamNegException | TamGrdException e) {
                    String novoValor = JOptionPane.showInputDialog(
                        null,
                        e.getMessage() + "\nPor favor, digite um novo valor:",
                        "Erro no Tamanho",
                        JOptionPane.WARNING_MESSAGE
                    );
                    txtTam.setText(novoValor);
                }
            }

            c1 = oprCac.insCac(c1);

            if (c1 != null) {
                JOptionPane.showMessageDialog(
                    null,
                    "Cadastro realizado com sucesso!",
                    "Inserção de Cacto",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Nome já existe!",
                    "Inserção de Cacto",
                    JOptionPane.ERROR_MESSAGE
                );
                txtNome.setText("");
                txtNome.requestFocus();
            }

        }// fim try
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                null,
                "Erro de formato (provável inserção de letra ao invés de número) em um dos campos. Verifique os valores de Andar, Espinhos ou Temperatura.",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
     
    public void limpar(){
        txtNome.setText("");
        txtGrp.setText("");
        txtTolSeca.setText("");
        txtQuantEsp.setText("");
        txtTemp.setText("");
        txtIlumAmb.setText("");
        txtCom.setText("");
        txtAndar.setText("");
        txtTam.setText("");
        txtNome.requestFocus();
    }
    public void dados(){
        txtNome.setText(c1.getNome());
        txtGrp.setText(c1.getGrupoPlanta());
        txtTolSeca.setText(c1.getToleranciaSeca());
        txtQuantEsp.setText(Integer.toString(c1.getQuantEspinhos()));
        txtTemp.setText(Float.toString(c1.getAmbiente().getTemperatura()));
        txtIlumAmb.setText(c1.getAmbiente().getIluminacao());
        txtCom.setText(c1.getAmbiente().getLocalizacao().getNomeComodo());
        txtAndar.setText(Integer.toString(c1.getAmbiente().getLocalizacao().getAndarComodo()));
        txtTam.setText(Double.toString(c1.getTamanho()));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadCacto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlter;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btInsere;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRmv;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jspCac;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblIlumAmb;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQntEsp;
    private javax.swing.JLabel lblTam;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTolSeca;
    private javax.swing.JTable tbCac;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtGrp;
    private javax.swing.JTextField txtIlumAmb;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantEsp;
    private javax.swing.JTextField txtTam;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtTolSeca;
    // End of variables declaration//GEN-END:variables
}
